### PR TITLE
Add DART videos to gallery

### PR DESCRIPTION
**Pull request by JustinPrivitera**
Resolves https://github.com/visit-dav/visit/issues/19611

### CODE REVIEW

**Review by markcmiller86 — COMMENTED** [review]
@JustinPrivitera this looks great!  There is one additional step...to create thumbnails of the images that are max 150 piexels in width and height @ 72 dpi. And, you have to name the files to match up what the liquid-processing is going to look for when the site regens. If you have `image: LICIAmovie.jpg` in frontmatter, then you need `LICIAmovie-thumb.jpg` in `images` directory too. Does this make sense?

**Comment by JustinPrivitera** [comment]
Do the thumbnails need to be square images?

What is frontmatter?

**Comment by JustinPrivitera** [comment]
@markcmiller86

**Comment by markcmiller86** [comment]
@JustinPrivitera no the thumbnails do not have to be square...well, if they are square, it probably looks better. But just max of 150 pixels in either width or height.

Frontmatter is that stuff you put at the top of the file between the `---` lines, https://jekyllrb.com/docs/step-by-step/03-front-matter/.

**Comment by JustinPrivitera** [comment]
Ok @markcmiller86 I added thumbnails as you requested.

**Comment by markcmiller86** [comment]
@JustinPrivitera do you have anyone you can "credit" with the images/movies or data used to produce them? See for example, https://visit-dav.github.io/visit-website/examples/ex41/ and https://github.com/visit-dav/visit-website/blob/gh-pages/_examples/ex41.md

Its fine if you don't. Just wanna credit people when we know who.

**Comment by JustinPrivitera** [comment]
I'll ask the person who provided me the videos.

**Comment by JustinPrivitera** [comment]
@markcmiller86 added image/video credits.

**Review by markcmiller86 — APPROVED** [review]

**Comment by JustinPrivitera** [comment]
Thanks for your help @markcmiller86!

**Pull request merged**
